"""Replace IMBMember table with IMBUser table

Revision ID: adbe7db7c883
Revises: 19ee01761281
Create Date: 2019-02-27 20:20:05.131747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbe7db7c883'
down_revision = '19ee01761281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imb_user_name'), 'imb_user', ['name'], unique=True)
    op.create_index(op.f('ix_imb_user_username'), 'imb_user', ['username'], unique=True)
    op.drop_index('ix_imb_member_name', table_name='imb_member')
    op.drop_index('ix_imb_member_username', table_name='imb_member')
    op.drop_table('imb_member')
    op.add_column('visit', sa.Column('imb_user', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.create_foreign_key(None, 'visit', 'imb_user', ['imb_user'], ['id'])
    op.drop_column('visit', 'imb_member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('imb_member', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.create_foreign_key(None, 'visit', 'imb_member', ['imb_member'], ['id'])
    op.drop_column('visit', 'imb_user')
    op.create_table('imb_member',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_imb_member_username', 'imb_member', ['username'], unique=1)
    op.create_index('ix_imb_member_name', 'imb_member', ['name'], unique=1)
    op.drop_index(op.f('ix_imb_user_username'), table_name='imb_user')
    op.drop_index(op.f('ix_imb_user_name'), table_name='imb_user')
    op.drop_table('imb_user')
    # ### end Alembic commands ###
