"""Create IMB members table

Revision ID: b70dc221a2fd
Revises:
Create Date: 2019-02-24 21:01:39.394548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70dc221a2fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imb_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imb_member_name'), 'imb_member', ['name'], unique=True)
    op.create_index(op.f('ix_imb_member_username'), 'imb_member', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imb_member_username'), table_name='imb_member')
    op.drop_index(op.f('ix_imb_member_name'), table_name='imb_member')
    op.drop_table('imb_member')
    # ### end Alembic commands ###
